# Generated by Django 6.0.1 on 2026-01-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_is_featured_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y-%m-%d', verbose_name='Featured Image'),
        ),
    ]
